project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: rdatatable.github.io/theraft
  description: ""
  navbar:
    right:
      - text: About
        href: blog.qmd 
      - icon: github
        href: https://github.com/rdatatable
      - icon: mastodon
        href: https://fosstodon.org/@r_data_table
      - icon: cloud
        href: https://bsky.app/profile/rdatatable.bsky.social
      - icon: twitter
        href: https://twitter.com/r_data_table
      - icon: envelope
        href: "mailto:r.data.table@gmail.com"
        
format:
  html:
    theme: [solar, custom.scss]
    css: styles.css

editor: visual

